id: P6B84B8B7
initial_creation_type: input
source_metadata:
  title: Bodhicitta Series
  language: en
  description: Texts on the subject of bodhicitta (byang chub sems), which (on the
    relative level, at least) is the compassionate wish to attain enlightenment for
    the sake of all living beings—and has been variously translated into English as
    'thought of enlightenment', 'awakening-mind', 'spirit of awakening', etc.
  volume:
    51829ff9c95b4ad39f42f5728e559a3c:
      title: Advice for Tenzin Jamchen
      parent: Advice
    c613ff967c2c45ca99ea99f463d5ff83:
      title: Bodhicitta Aspiration
      parent: Aspirations
    563c21a153c444fd81a71e57a5b8b443:
      title: Aspiration to Generate Bodhicitta, Utterly Pure and Supreme
      parent: Aspirations
    5205dae7009c49518a0f9a2591006892:
      title: An Extensive Commentary on the Four Immeasurables
      parent: Commentaries
    5140da585b0c42a394e4e6d7d5f39ade:
      title: A Brief Commentary on the Refuge & Bodhichitta Prayer known as Sangyé
        Chö Tsok Ma
      parent: Commentaries
    3df618c16e3e4a5d92e094b6d2572a67:
      title: An Essential Instruction on Refuge and Bodhichitta
      parent: Commentaries
    5eab2605ddae47fda5d4f3342d2647cc:
      title: How Our Supreme Teacher Generated Bodhicitta and Other Topics
      parent: History
    9f32521026d34367be7dde98fc4e1896:
      title: Daily Confession (from the Vajrapañjara Tantra)
      parent: Practices
    7a39fc78340745b787faaebe7f8ceadb:
      title: The Ritual of the Bodhisattva Vow According to the Tradition of Patrul
        Rinpoche
      parent: Practices
    5bb45d5ec1a5457794b9fd31766cee02:
      title: Verses of Refuge and Bodhicitta
      parent: Practices
    91b969142f7349d094a04266cf6dd8b8:
      title: The Three Noble Principles
      parent: Three Noble Principles
created_at: '2022-03-01T03:03:50.797598'
last_modified_at: '2022-03-01T03:03:50.797604'
